import scopus_helper as sh

if __name__ == '__main__':
    # p = sh.search_profiles('Daniel', 'Acuna', 'Rehabilitation Institute of Chicago')
    # p = sh.search_profiles('K', 'Lebron-Milad', '*')
    p = {u'entry': [{u'@_fa': u'true',
                     u'affiliation-current': {u'affiliation-city': u'Evanston',
                                              u'affiliation-country': u'United States',
                                              u'affiliation-id': u'60007363',
                                              u'affiliation-name': u'Northwestern University',
                                              u'affiliation-url': u'http://api.elsevier.com/content/affiliation/affiliation_id/60007363'},
                     u'dc:identifier': u'AUTHOR_ID:8901389500',
                     u'document-count': u'9',
                     u'eid': u'9-s2.0-8901389500',
                     u'link': [{u'@_fa': u'true',
                                u'@href': u'http://api.elsevier.com/content/author/author_id/8901389500',
                                u'@ref': u'self'},
                               {u'@_fa': u'true',
                                u'@href': u'http://api.elsevier.com/content/search/author?query=au-id%288901389500%29',
                                u'@ref': u'search'},
                               {u'@_fa': u'true',
                                u'@href': u'http://www.scopus.com/author/citedby.url?partnerID=HzOxMe3b&citedAuthorId=8901389500&origin=inward',
                                u'@ref': u'scopus-citedby'},
                               {u'@_fa': u'true',
                                u'@href': u'http://www.scopus.com/authid/detail.url?partnerID=HzOxMe3b&authorId=8901389500&origin=inward',
                                u'@ref': u'scopus-author'}],
                     u'name-variant': [{u'@_fa': u'true',
                                        u'given-name': u'Daniel E',
                                        u'initials': u'D.E.',
                                        u'surname': u'Acu\xf1a'},
                                       {u'@_fa': u'true',
                                        u'given-name': u'Daniel E.',
                                        u'initials': u'D.E.',
                                        u'surname': u'Acuna'},
                                       {u'@_fa': u'true',
                                        u'given-name': u'Daniel',
                                        u'initials': u'D.',
                                        u'surname': u'Acuna'}],
                     u'preferred-name': {u'given-name': u'Daniel E.',
                                         u'initials': u'D.E.',
                                         u'surname': u'Acu\xf1a'},
                     u'prism:url': u'http://api.elsevier.com/content/author/author_id/8901389500',
                     u'subject-area': [{u'$': u'Biochemistry, Genetics and Molecular Biology (all)',
                                        u'@abbrev': u'BIOC',
                                        u'@force-array': u'true',
                                        u'@frequency': u'8'},
                                       {u'$': u'Computer Science (all)',
                                        u'@abbrev': u'COMP',
                                        u'@force-array': u'true',
                                        u'@frequency': u'6'},
                                       {u'$': u'Agricultural and Biological Sciences (all)',
                                        u'@abbrev': u'AGRI',
                                        u'@force-array': u'true',
                                        u'@frequency': u'4'}]}],
         u'link': [{u'@_fa': u'true',
                    u'@href': u'http://api.elsevier.com:80/content/search/author?start=0&count=25&query=authlastname%28acuna%29+and+authfirst%28daniel%29+and+affil%28rehabilitation+institute+of+chicago%29',
                    u'@ref': u'self',
                    u'@type': u'application/json'},
                   {u'@_fa': u'true',
                    u'@href': u'http://api.elsevier.com:80/content/search/author?start=0&count=25&query=authlastname%28acuna%29+and+authfirst%28daniel%29+and+affil%28rehabilitation+institute+of+chicago%29',
                    u'@ref': u'first',
                    u'@type': u'application/json'}],
         u'opensearch:Query': {u'@role': u'request',
                               u'@searchTerms': u'authlastname%28acuna%29+and+authfirst%28daniel%29+and+affil%28rehabilitation+institute+of+chicago%29',
                               u'@startPage': u'0'},
         u'opensearch:itemsPerPage': u'1',
         u'opensearch:startIndex': u'0',
         u'opensearch:totalResults': u'1'}
    # before using the function you need to specify the list of API keys that you have available
    sh.ElsevierApiKeyCycler.key_list = []
    profile = sh.get_profile('8868165800')
    print profile
